image: maven:3.8.4-openjdk-17

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean compile
  tags:
    - GAUFRE_RUNNER

test:
  stage: test
  script:
    - mvn test
  tags:
    - GAUFRE_RUNNER

deploy:
  stage: deploy
  script:
    - echo "Deploying...."
  tags:
    - GAUFRE_RUNNER
